// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Post.Infra;

#nullable disable

namespace Post.Api.Infrastructure.Migrations
{
    [DbContext(typeof(PostDBContext))]
    [Migration("20230503092303_InitPostDB")]
    partial class InitPostDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Post.Domain.Entities.CategoryAggregate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "تکنولوژی"
                        },
                        new
                        {
                            Id = 2,
                            Title = "فین تک"
                        });
                });

            modelBuilder.Entity("Post.Domain.Entities.PostAggregate.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "ردمی نوت ۱۱ پرو 5G در مقایسه‌با نسل قبل بهبود معناداری تجربه نمی‌کند و در بخش‌هایی همچون عملکرد و دوربین، رقبای سرسختی دارد. با بررسی ردمی نوت ۱۱ پرو همراه باشید.",
                            Headline = "ردمی نوت ۱۱ پرو 5G در مقایسه‌با نسل قبل بهبود معناداری تجربه نمی‌کند و در بخش‌هایی همچون عملکرد و دوربین، رقبای سرسختی دارد. با بررسی ردمی نوت ۱۱ پرو همراه باشید.",
                            Keywords = "ردمی موبایل شیائومی",
                            Title = "بررسی ردمی نوت ۱۱ پرو 5G شیائومی"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "براساس شایعه‌ای جدید، سامسونگ قصد دارد اواسط بهمن مراسم Galaxy Unpacked را برای رونمایی گوشی‌های سری گلکسی اس ۲۳ برگزار کند.",
                            Headline = "براساس شایعه‌ای جدید، سامسونگ قصد دارد اواسط بهمن مراسم Galaxy Unpacked را برای رونمایی گوشی‌های سری گلکسی اس ۲۳ برگزار کند.",
                            Keywords = "سامسونگ گلکسی رونمایی موبایل",
                            Title = "احتمال رونمایی گلکسی اس ۲۳ در هفته دوم بهمن قوت گرفت"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "گلکسی واچ ۴ و گلکسی واچ ۵ هنگام انجام تجزیه‌و‌تحلیل امپدانس بیوالکتریک (BIA) به دقتی قابل مقایسه با معیارهای آزمایشگاهی اما کمتر از آن دست می‌یابد.",
                            Headline = "گلکسی واچ ۴ و گلکسی واچ ۵ هنگام انجام تجزیه‌و‌تحلیل امپدانس بیوالکتریک (BIA) به دقتی قابل مقایسه با معیارهای آزمایشگاهی اما کمتر از آن دست می‌یابد.",
                            Keywords = "پوشیدنی گلکسی واچ",
                            Title = "آنالیز ترکیب بدن گلکسی واچ 4 و گلکسی واچ 5 نسبتاً دقیق است"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "براساس گزارشی جدید، هدفون Buds 4 شیائومی در رویداد دهم آذر با قیمتی مقرون‌به‌صرفه‌تر از نسخه‌ی Buds 4 پرو فعلی، رونمایی خواهد شد.",
                            Headline = "براساس گزارشی جدید، هدفون Buds 4 شیائومی در رویداد دهم آذر با قیمتی مقرون‌به‌صرفه‌تر از نسخه‌ی Buds 4 پرو فعلی، رونمایی خواهد شد.",
                            Keywords = "پوشیدنی شیائومی هدفون",
                            Title = "قیمت هدفون Buds 4 و ساعت هوشمند Watch S2 شیائومی پیش از رونمایی اعلام شد"
                        });
                });

            modelBuilder.Entity("Post.Domain.Entities.PostAggregate.PostMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedias");
                });

            modelBuilder.Entity("Post.Domain.Entities.PostAggregate.Post", b =>
                {
                    b.HasOne("Post.Domain.Entities.CategoryAggregate.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Post.Domain.Entities.PostAggregate.PostMedia", b =>
                {
                    b.HasOne("Post.Domain.Entities.PostAggregate.Post", null)
                        .WithMany("Medias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Post.Domain.Entities.PostAggregate.Post", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
