global using Microsoft.Identity.Client;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Xunit;
global using Post.Api.Controllers;
global using Post.Application.RepositoryProxies.Contracts;